[package]
name = "sunlib"
version = "0.1.0"
edition = "2021"

[dependencies]
units = {path="../units"}
exmex = {version="0.20.3", features = ["partial"]}
toml = "0.8.20"
serde = {version="1.0.217", features=["derive"]}
rand = "0.8.0"
roots = "0.0.8"
mathru = "0.15.5"
tabled = "0.19.0"