[[quantity]]
symbol = "a"
measured = 1.0
units = "V"
typeb = [
    {Normal = {name = "ABC", stddev = 2}},
#    {Uniform = {name = "DEF", a = 2.5}},
]
#typea = [1,2,3,2,1,4,2,3,2,1,2,3,1]

[[quantity]]
symbol = "b"
measured = 1.0
units = "A"
typeb = [
    {Normal = {name = "TypeB", stddev = 1.5}}
]

[[function]]
symbol = "f"
expr = "a/b"
units = "ohm"